#!/bin/sh

# Use neovim for vim if present.
 [ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
	}

# Aliases

alias dotfiles='/usr/bin/git --git-dir=$HOME/Templates/t14sdots --work-tree=$HOME'
# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
alias ~='cd ~'
alias -- -='cd -'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'

alias ping="ping -c 5"
alias lf="lfub"
alias not="xed"
alias tmpsil="sudo for i in /tmp/* ; do rm -r "$i" ; done"
alias ekran="sh .screenlayout/dock.sh"
alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0| grep -E "state|to\ full|percentage"'
alias ll='ls -alF'
alias first='sed -n "/ installed $1/{s/].*/]/p;q}" /var/log/pacman.log'
alias wiki="nvim -c VimwikiIndex"
alias ipadres="curl ipinfo.io/ip"
alias bc="bc -l"
alias la='ls -A'
alias l='ls -CF'
alias lh='ls -lh'
alias mx='tmuxinator'
alias stat='glances'
alias oldvim="\vim"
alias gvim=nvim
alias pbcopy="xclip -selection clipboard"
alias pbpaste="xclip -selection clipboard -o"
alias home="cd ~"
alias c="clear"
alias h="home"
alias p="cat"
alias pd="pwd"
alias ttr="trans -b :tr"
alias ten="trans -b tr:en"
alias tfen="trans -b tr:en file://Documents/Notes/vimwiki/notes/tasks/blogging.md"
alias u='cd ..'
alias hd='sh ~/deploy.sh'
alias ka="killall" \
  son="grep -i installed /var/log/pacman.log" \
	mkd="mkdir -pv" \
	cfi3="e ~/.config/i3/config" \
	cfbs="e ~/.config/bspwm/bspwmrc" \
	cfsx="e ~/.config/sxhkd/sxhkdrc" \
	cfal="e ~/.config/shell/aliases" \
	cfex="e ~/.config/shell/exports" \
	cfvi="e ~/.config/nvim/init.vim" \
	cfdw="e $HOME/Templates/suckless/dwm/config.h" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	r="ranger" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	x="nsxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	YT="yt-dlp --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	yt="/usr/bin/ytfzf" \
	upc="checkupdates" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner"
alias duf='du -hsx * | sort -rh | head -5'
alias treeacl='tree -A -C -L 2'
alias hava='wttr Istanbul'
alias wake='systemctl restart NetworkManager.service'
alias windows='sudo mount -t cifs //192.168.0.26/Ortak /mnt/ortak'
alias notgit='rsync -chavzP --stats --delete Documents/Notes/vimwiki eorus-home:~/Documents/notes/'
alias notgel='rsync -chavzP --stats --delete eorus-home:~/Documents/notes/vimwiki /home/eorus/Documents/Notes/'

alias yedek="sudo rsync -aAXv --delete --exclude=/dev/* --exclude=/proc/* --exclude=/sys/* --exclude=/tmp/* --exclude=/run/* --exclude=/mnt/* --exclude=/media/* --exclude="swapfile" --exclude="lost+found" --exclude="/home/$USER/.cache" --exclude="/home/$USER/Downloads" --exclude="/home/$USER/.VirtualBoxVMs"--exclude="/home/$USER/.ecryptfs" --exclude=/home/$USER/Desktop --exclude=/home/$USER/.cache --exclude=/home/$USER/.debug --exclude=/home/$USER/.dbus --exclude=/home/$USER/.gvfs --exclude=/home/$USER/.local/share/gvfs-metadata --exclude=/home/$USER/.local/share/Trash --exclude=/home/$USER/.recently-used --exclude=/home/$USER/.thumbnails --exclude=/home/$USER/.xsession-errors --exclude=/home/$USER/.Trash --exclude=/home/$USER/.steam --exclude=/home/$USER/Videos --exclude=/home/$USER/Steam / /run/media/eorus/Backups/arch"

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.
alias fzf='fzf --preview="head -$LINES {}"'
vf() { fzf | xargs -r -I % $EDITOR % ;}
alias timer='echo "Timer started. Stop with Ctrl-D." && date "+%a, %d %b %H:%M:%S" && time cat && date "+%a, %d %b %H:%M:%S"'
alias mp3-dl='yt-dlp --ignore-config --extract-audio \
    --audio-format "mp3" --audio-quality 0 --embed-thumbnail --embed-metadata \
    --output "$HOME/Downloads/%(title)s.%(ext)s"'
