#!/bin/sh
# ~/.config/X11/xprofile - X session startup config
#setxkbmap tr
# Load X resources
xrdb -merge -I"$HOME/.config/X11" "$HOME/.config/X11/xresources"

# Set cursor
xsetroot -cursor_name left_ptr

# Set keyboard repeat rate
xset r rate 300 50 &

# DPMS power management (adjust times as you like)
xset dpms 300 600 0 &

# Turn off bell sound
xset b off &

# Load color schemes if your Xresources references Xcolors
# (if you source Xcolors separately, add this)
# xrdb -merge "$HOME/.config/X11/Xcolors"

# Run background utilities
redshift-gtk &
xmodmap -e 'keycode 135 = Super_R' &

# Start MPD if not running
[ ! -s ~/.config/mpd/pid ] && mpd &

# Remove mouse cursor when idle
unclutter &

# Notifications daemon
dunst &

# Caffeine to inhibit sleep
caffeine &

# Clipboard utilities
xclip &


picom --config ~/.config/picom/picom.conf -b &

# Start Network Manager applet (if you want)
# sleep 2 && nm-applet &
#
# 40% brightness at startup
brightnessctl set 40%

# Compositor (picom)
picom --config ~/.config/picom/picom.conf --experimental-backends -b &

# Wallpaper script
"$HOME/Pictures/wallpaper.sh" &
