#! /bin/sh

# ┌─────────────┐
# │CONFIGURATION│
# └─────────────┘

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -g 1920x1200+0+0

bspc config border_radius                 8
bspc config border_width                  5
bspc config window_gap                    5
#bspc config top_padding                   1
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# ┌─────────────┐
# │COLORS       │
# └─────────────┘

bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	        "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

# ┌─────┐
# │RULES│
# └─────┘

# fix programs starting in floating mode
bspc rule -a Gimp desktop=^6 follow=on state=floating
bspc rule -a Zathura state=tiled
bspc rule -a mpv state=floating

# ┌────────────────┐
# │STARTUP PROGRAMS│
# └────────────────┘

xsetroot -cursor_name left_ptr
pkill -USR1 -x sxhkd || /usr/bin/sxhkd &
#picom --config $HOME/.config/picom.conf &
~/.config/polybar/launch.sh &
#~/Pictures/wallpaper.sh &
